# Generated by Django 4.1 on 2023-11-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockClusterGroupParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("n_steps", models.IntegerField()),
                ("tickers", models.JSONField(default=list)),
                ("target_cols", models.JSONField(default=list)),
                ("interval", models.CharField(max_length=10)),
                ("cluster_features", models.JSONField(default=list)),
                ("scaling_dict", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
