# Generated by Django 4.1 on 2023-11-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockClusterGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_clusters", models.IntegerField(default=0)),
                (
                    "group_params",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_params",
                        to="ClusterPipeline.stockclustergroupparams",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.IntegerField(default=-1)),
                (
                    "cluster_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_group",
                        to="ClusterPipeline.stockclustergroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
