# Generated by Django 4.1 on 2023-11-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0002_stockclustergroup_stockcluster"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportedParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("features", models.JSONField(default=list)),
            ],
        ),
    ]
