# Generated by Django 4.1 on 2023-11-13 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0003_supportedparams"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("steps_in_future", models.IntegerField(default=0)),
                ("dir_accuracy", models.FloatField(default=0)),
                ("weighted_dir_acc", models.FloatField(default=0)),
                ("predicted_return", models.FloatField(default=0)),
                ("actual_return", models.FloatField(default=0)),
                ("train_set_length", models.IntegerField(default=0)),
                ("test_set_length", models.IntegerField(default=0)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster",
                        to="ClusterPipeline.stockcluster",
                    ),
                ),
            ],
        ),
    ]
