# Generated by Django 4.1 on 2023-11-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ClusterPipeline",
            "0005_stockcluster_file_string_supportedparams_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stockclustergroupparams",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
