# Generated by Django 4.1 on 2023-11-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0006_stockclustergroupparams_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockclustergroupparams",
            name="X_feature_dict",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="stockclustergroupparams",
            name="y_feature_dict",
            field=models.JSONField(default=dict),
        ),
    ]
