# Generated by Django 4.1 on 2023-11-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0007_stockclustergroupparams_x_feature_dict_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockcluster",
            old_name="file_string",
            new_name="elements_file_string",
        ),
        migrations.AddField(
            model_name="stockcluster",
            name="model_file_string",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="stepresult",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cluster_results",
                to="ClusterPipeline.stockcluster",
            ),
        ),
    ]
