# Generated by Django 4.1 on 2023-11-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ClusterPipeline",
            "0008_rename_file_string_stockcluster_elements_file_string_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SequenceElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq_y_scaled", models.JSONField(default=list)),
                ("seq_x_scaled", models.JSONField(default=list)),
                ("isTrain", models.BooleanField(default=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("ticker", models.CharField(max_length=10)),
                ("n_steps", models.IntegerField(default=0)),
                (
                    "cluster",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence_elements",
                        to="ClusterPipeline.stockcluster",
                    ),
                ),
            ],
        ),
    ]
