# Generated by Django 4.1 on 2023-11-14 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0009_sequenceelement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sequenceelement",
            name="seq_x_scaled",
        ),
        migrations.RemoveField(
            model_name="sequenceelement",
            name="seq_y_scaled",
        ),
        migrations.AddField(
            model_name="sequenceelement",
            name="seq_x_scaled_path",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="sequenceelement",
            name="seq_y_scaled_path",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="sequenceelement",
            name="cluster",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequence_elements",
                to="ClusterPipeline.stockcluster",
            ),
        ),
    ]
