# Generated by Django 4.1 on 2023-11-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0011_sequenceelement_seq_x_scaled_string_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockclustergroup",
            name="test_labels",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="stockclustergroup",
            name="train_labels",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="SequenceElement",
        ),
    ]
