# Generated by Django 4.1 on 2023-11-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0012_stockclustergroup_test_labels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportedparams",
            name="cuma_features",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="supportedparams",
            name="pct_chg_features",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="supportedparams",
            name="price_features",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="supportedparams",
            name="rolling_features",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="supportedparams",
            name="trend_features",
            field=models.JSONField(default=list),
        ),
    ]
