# Generated by Django 4.1 on 2023-11-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0013_supportedparams_cuma_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockclustergroupparams",
            name="training_features",
            field=models.JSONField(default=list),
        ),
    ]
