# Generated by Django 4.1 on 2023-11-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0014_stockclustergroupparams_training_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepresult",
            name="p_l",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="stockcluster",
            name="cluster_metrics",
            field=models.JSONField(default=dict),
        ),
    ]
