# Generated by Django 4.1 on 2023-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0015_stepresult_p_l_stockcluster_cluster_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepresult",
            name="actual_values",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="stepresult",
            name="predicted_values",
            field=models.JSONField(default=list),
        ),
    ]
