# Generated by Django 4.1 on 2023-12-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0017_remove_stepresult_cluster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rnnmodel",
            name="model_type_str",
            field=models.CharField(default="None", max_length=1000),
        ),
        migrations.AddField(
            model_name="rnnmodel",
            name="num_encoder_layers",
            field=models.IntegerField(default=0),
        ),
    ]
