# Generated by Django 4.1 on 2023-12-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0018_rnnmodel_model_type_str_rnnmodel_num_encoder_layers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rnnmodel",
            name="model_features",
            field=models.JSONField(default=list),
        ),
    ]
