# Generated by Django 4.1 on 2023-12-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0019_alter_rnnmodel_model_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="rnnmodel",
            name="model_metrics",
            field=models.JSONField(default=dict),
        ),
    ]
