# Generated by Django 4.1 on 2023-12-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0020_rnnmodel_model_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcluster",
            name="centroud",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="stockclustergroupparams",
            name="cluster_features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="stockclustergroupparams",
            name="training_features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
