# Generated by Django 4.1 on 2023-12-28 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0021_stockcluster_centroud_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockcluster",
            old_name="centroud",
            new_name="centroid",
        ),
    ]
