# Generated by Django 4.1 on 2023-12-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0023_prediction_stockpredidction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StockPredidction",
            new_name="StockPrediction",
        ),
    ]
