# Generated by Django 4.1 on 2024-01-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0024_rename_stockpredidction_stockprediction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockclustergroupparams",
            name="name",
            field=models.CharField(default="", max_length=400),
        ),
    ]
