# Generated by Django 4.1 on 2024-01-19 05:35

import ClusterPipeline.models.Predictions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ClusterPipeline",
            "0026_remove_stockclustergroupparams_x_feature_dict_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ForcastTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockForcastTimeline",
            fields=[
                (
                    "forcasttimeline_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ClusterPipeline.forcasttimeline",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("interval", models.CharField(max_length=10)),
                ("prediction_start_date", models.DateField()),
                ("prediction_end_date", models.DateField()),
                (
                    "df_file",
                    models.FileField(
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            bases=("ClusterPipeline.forcasttimeline",),
        ),
        migrations.AddField(
            model_name="stockprediction",
            name="forcast_timeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ClusterPipeline.stockforcasttimeline",
            ),
        ),
    ]
