# Generated by Django 4.1 on 2024-01-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ClusterPipeline",
            "0026_remove_stockclustergroupparams_x_feature_dict_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rnnmodel",
            name="target_feature_type",
            field=models.CharField(default="cumulative", max_length=1000),
        ),
    ]
