# Generated by Django 4.1 on 2024-01-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0027_forcasttimeline_stockforcasttimeline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockprediction",
            name="dir_path",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
