# Generated by Django 4.1 on 2024-01-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0027_rnnmodel_target_feature_type"),
        ("ClusterPipeline", "0028_stockprediction_dir_path"),
    ]

    operations = []
