# Generated by Django 4.1 on 2024-02-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0029_stockforcasttimeline_final_prediction_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockclustergroupparams",
            name="model_params",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
