# Generated by Django 4.1 on 2024-02-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ClusterPipeline",
            "0031_alter_stockforcasttimeline_final_prediction_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockforcasttimeline",
            name="df_file",
        ),
        migrations.AlterField(
            model_name="modelprediction",
            name="rnn_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rnn_model_predictions",
                to="ClusterPipeline.rnnmodel",
            ),
        ),
        migrations.AlterField(
            model_name="modelprediction",
            name="stock_prediction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_model_predictions",
                to="ClusterPipeline.stockprediction",
            ),
        ),
    ]
