# Generated by Django 4.1 on 2024-02-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0029_merge_20240126_2111"),
        ("ClusterPipeline", "0032_remove_stockforcasttimeline_df_file_and_more"),
    ]

    operations = []
