# Generated by Django 4.1 on 2024-02-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0033_merge_20240214_0516"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportedparams",
            name="lag_features",
            field=models.JSONField(default=list),
        ),
    ]
