# Generated by Django 4.1 on 2024-04-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0035_supportedparams_momentum_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="rnnmodel",
            name="taget_features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
