# Generated by Django 4.1 on 2024-04-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ClusterPipeline", "0036_rnnmodel_taget_features"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rnnmodel",
            old_name="taget_features",
            new_name="target_features",
        ),
    ]
